version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo "Installing dependencies for all three functions..."
      # Installs libraries directly into the function folders
      - pip install pypdf typing_extensions -t PDFtoTXT/
      - pip install requests requests_aws4auth -t Upload-to-search/
      - pip install requests requests_aws4auth -t Search-Function/
      
  build:
    commands:
      - echo "Packaging infrastructure for all functions..."
      # This command zips folders and uploads them to S3, creating 'lambdaoutput.yaml'
      - aws cloudformation package --template-file template.yaml --s3-bucket search-artifacts-store --output-template-file lambdaoutput.yaml
      
artifacts:
  files:
    - lambdaoutput.yaml
    - template.yaml