version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo "Installing dependencies..."
      - pip install pypdf typing_extensions -t PDFtoTXT/
      - pip install requests requests_aws4auth -t Upload-to-search/
      
  build:
    commands:
      - echo "Packaging infrastructure..."
      # UPDATED: Pointing to the new 'template.yaml' in the root
      - aws cloudformation package --template-file template.yaml --s3-bucket search-artifacts-store --output-template-file lambdaoutput.yaml
      
  post_build:
    commands:
      - echo "Deploying..."
      - aws cloudformation deploy --template-file lambdaoutput.yaml --stack-name pdf-automation-v1 --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM --no-fail-on-empty-changeset