version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo "Cleaning old local libraries..."
      # This ensures we don't zip up broken or wrong-version local files
      - rm -rf pypdf typing_extensions
      - echo "Installing fresh dependencies..."
      - pip install pypdf -t .
  build:
    commands:
      - echo "Packaging infrastructure..."
      - aws cloudformation package --template-file PDFtoTXT/PDFtoTXT/pdftotxt.yaml --s3-bucket search-artifacts-store --output-template-file temp.yaml
      - sed '1s/^\xef\xbb\xbf//' temp.yaml > lambdaoutput.yaml
  post_build:
    commands:
      - echo "Deploying to AWS..."
      - aws cloudformation deploy --template-file lambdaoutput.yaml --stack-name pdf-automation-v1 --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM --no-fail-on-empty-changeset