version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
  build:
    commands:
      - echo "Starting clean package..."
      # Updated paths to match your GitHub folder structure
      - aws cloudformation package --template-file PDFtoTXT/PDFtoTXT/pdftotxt.yaml --s3-bucket search-artifacts-store --output-template-file temp.yaml
      # This line removes the hidden characters that break CloudFormation
      - sed '1s/^\xef\xbb\xbf//' temp.yaml > lambdaoutput.yaml

   post_build:
    commands:
      - echo "Deploying updated Lambda..."
      - aws cloudformation package --template-file template.yaml --s3-bucket search-artifacts-store --output-template-file packaged.yaml
      - aws cloudformation deploy --template-file packaged.yaml --stack-name pdf-to-text-stack --capabilities CAPABILITY_IAM

artifacts:
  files:
    - lambdaoutput.yaml
    - PDFtoTXT/PDFtoTXT/pdftotxt.yaml
