version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - echo "Installing dependencies directly into the source folder..."
      # Install directly into the folder CloudFormation will zip
      - pip install pypdf typing_extensions -t PDFtoTXT/PDFtoTXT/
  build:
    commands:
      - echo "Packaging infrastructure..."
      # This command zips everything inside PDFtoTXT/PDFtoTXT/
      - aws cloudformation package --template-file PDFtoTXT/PDFtoTXT/pdftotxt.yaml --s3-bucket search-artifacts-store --output-template-file lambdaoutput.yaml
  post_build:
    commands:
      - echo "Deploying..."
      - aws cloudformation deploy --template-file lambdaoutput.yaml --stack-name pdf-automation-v1 --capabilities CAPABILITY_IAM CAPABILITY_NAMED_IAM --no-fail-on-empty-changeset