AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Automated PDF to Text Converter for us-east-1.

Resources:
  pdftotxt:
    Type: 'AWS::Serverless::Function'
    Properties:
      FunctionName: PDFToText-Automated
      Handler: lambda_function.lambda_handler
      Runtime: python3.10
      CodeUri: .
      Description: 'Extracts text from PDFs automatically via CI/CD'
      MemorySize: 512
      Timeout: 900
      Role: 'arn:aws:iam::779803046124:role/lambda_s3'
      Environment:
        Variables:
          TARGET_BUCKET: gl-inter-store-2026
          DEPLOY_TIMESTAMP: "2026-02-21-v3" # Change this slightly every time you push to force an update
